name: "Factorio-check"
description: "Linting for factorio scenarios and mods."
author: "Danny Farrell <16297104+danpf@users.noreply.github.com>"
inputs:
  directory:
    description: "Directory to run the linting."
    required: false
    default: "${{ github.workspace }}"
runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3

    - name: Cache Docker layers
      uses: actions/cache@v4
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-dev1.1.104-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-dev1.1.104-

    - run: |
        docker buildx build \
          --build-arg SHA256=8e13353ab23d57989db7b06594411d30885de1a923f3a989d12749c1abc01583 \
          --build-arg VERSION=1.1.104 \
          --tag factorio-check-action \
          --cache-from=type=local,src=/tmp/.buildx-cache \
          --cache-to=type=local,dest=/tmp/.buildx-cache \
          --load \
          "${{ github.workspace }}" \
          -f "${{ github.workspace }}/docker/Dockerfile"
      shell: bash

    - run: |
        USER_ID=$(id -u)
        GROUP_ID=$(id -g)
        docker run --user ${USER_ID}:${GROUP_ID} --entrypoint lint-entrypoint.sh --rm -v "${{ inputs.directory }}":"${{ inputs.directory }}":ro factorio-check-action "${{ inputs.directory }}"
      shell: bash
