version: '2'
services:
  factorio:
    platform: linux/amd64
    entrypoint: /opt/factorio/bin/x64/factorio
    command:  ["--start-server-load-scenario", "Factorio-Biter-Battles"]
    build:
      context: ../
      dockerfile: docker/Dockerfile.fbb-test
      args:
        # Check buildinfo.json for supported versions and SHAs
        # https://github.com/factoriotools/factorio-docker/blob/master/buildinfo.json
        - VERSION=1.1.100
        - SHA256=9850dd146f93ee4da8ba06316591888860a4058c8548409cdfb5dd693abcd834
        - BASETAG=1.1.100-base
    ports:
      - "34197:34197/udp"
      - "27015:27015/tcp"
    # volumes:
    #   - /opt/factorio:/factorio
#    environment:
#      - PUID=1000
#      - PGID=1000
#      - UPDATE_MODS_ON_START=true
#      - USERNAME=FactorioUsername
#      - TOKEN=FactorioToken
#      - PORT=34198
#      - ADDR=::1
