name: Docker Hub Description
on:
  push:
    branches:
      - master
jobs:
  docker-description:
    runs-on: ubuntu-latest
    environment:
      name: cicd
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: danpfuw/factorio-check
