name: Docker Hub Description

on:
  push:
    branches:
      - master

jobs:
  docker-description:
    runs-on: ubuntu-latest
    environment:
      name: cicd
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v2.4.1
        if: ${{ secrets.DOCKER_USERNAME != '' && secrets.DOCKER_TOKEN != '' }}
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          repository: danpfuw/factorio-check
