name: Factorio Mod and Scenario Testing
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test:
    strategy:
      matrix:
        version_and_sha: [{version: 1.1.104, sha256: 8e13353ab23d57989db7b06594411d30885de1a923f3a989d12749c1abc01583}, {version: 1.1.101, sha256: 0688a6f615a87bf73d3f46b53dc423ee37cad3fc4412723f3d7450aed1638392}, {version: 1.1.100, sha256: 9850dd146f93ee4da8ba06316591888860a4058c8548409cdfb5dd693abcd834}]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    environment:
      name: cicd
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: danpfuw
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # TODO only on tag
      - name: Build and test base
        uses: docker/build-push-action@v5
        with:
          file: docker/Dockerfile
          tags: danpfuw/factorio-check:${{ matrix.version_and_sha.version }}
          build-args: |
            VERSION=${{ matrix.version_and_sha.version }}
            SHA256=${{ matrix.version_and_sha.sha256 }}
          load: true
      - name: Run simple-scenario linting
        run: |
          docker run --rm \
          -e LOGLEVEL=DEBUG \
          --entrypoint lint-entrypoint.sh \
          -t danpfuw/factorio-check:${{ matrix.version_and_sha.version }} \
          /opt/factorio-check-examples/simple-scenario
      - name: Run simple-scenario tests
        run: |
          docker run --rm \
          -e LOGLEVEL=DEBUG \
          --entrypoint run-factorio-test \
          -t danpfuw/factorio-check:${{ matrix.version_and_sha.version }} \
          --factorio_executable /opt/factorio/bin/x64/factorio \
          --factorio_scenario simple-scenario \
          --factorio_scenario_copy_dirs /opt/factorio-check-examples/simple-scenario

      - name: Run simple-mod linting
        run: |
          docker run --rm \
          -e LOGLEVEL=DEBUG \
          --entrypoint lint-entrypoint.sh \
          -t danpfuw/factorio-check:${{ matrix.version_and_sha.version }} \
          /opt/factorio-check-examples/simple-mod
      - name: Run simple-mod tests
        run: |
          docker run --rm \
          -e LOGLEVEL=DEBUG \
          --entrypoint run-factorio-test \
          -t danpfuw/factorio-check:${{ matrix.version_and_sha.version }} \
          --factorio_executable /opt/factorio/bin/x64/factorio \
          --factorio_mods_copy_dirs /opt/factorio-check-examples/simple-mod
      - name: Build and push base
        uses: docker/build-push-action@v5
        with:
          file: docker/Dockerfile
          tags: danpfuw/factorio-check:${{ matrix.version_and_sha.version }}
          build-args: |
            VERSION=${{ matrix.version_and_sha.version }}
            SHA256=${{ matrix.version_and_sha.sha256 }}
          push: true
