
name: Factorio Mod and Scenario Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up environment
      run: |
        sudo apt-get update
        sudo apt-get install -y lua5.3

    - name: Run local tests
      run: |
        cd tests/factorio-check
        lua main.lua

    - name: Build and run Docker tests
      run: |
        docker build -t factorio-headless .
        docker run factorio-headless lua tests/factorio-check/main.lua
