
name: Factorio Mod and Scenario Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        file: docker/Dockerfile
        tags: factorio-test-headless:latest

    - name: Build and run Docker tests
      run: docker run -it factorio-test-headless run-factorio-test --factorio_executable 
    # - name: Set up environment
    #   run: |
    #     sudo apt-get update
    #     sudo apt-get install -y lua5.3

    # - name: Run local tests
    #   run: |
    #     cd tests/factorio-check
    #     lua main.lua

