
name: Factorio Mod and Scenario Testing

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        file: docker/Dockerfile
        tags: danpf/factorio-test-headless:latest
        build-args: |
          VERSION=1.1.91
          SHA256=2288b21afb1d96aa06712a2ae2e31b9c45f0aa4a2e9dec041125d874f0781f6d
        cache-from: type=registry,ref=danpf/factorio-test-headless:latest
        cache-to: type=inline

    - name: Build and run Docker tests
      run: |
        docker run -it danpf/factorio-test-headless ls /opt/factorio/*
        docker run -it danpf/factorio-test-headless ls /opt/factorio/bin/*
        docker run -it danpf/factorio-test-headless run-factorio-test --help
        docker run -it danpf/factorio-test-headless run-factorio-test --factorio_executable /opt/factorio/bin/factorio
        # docker build --platform linux/amd64 . -t factoriotest  --build-arg VERSION=1.1.91 --build-arg SHA256=2288b21afb1d96aa06712a2ae2e31b9c45f0aa4a2e9dec041125d874f0781f6d -f docker/Dockerfile
        echo "done?"
    # - name: Set up environment
    #   run: |
    #     sudo apt-get update
    #     sudo apt-get install -y lua5.3

    # - name: Run local tests
    #   run: |
    #     cd tests/factorio-check
    #     lua main.lua

