
name: Factorio Mod and Scenario Testing

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        file: docker/Dockerfile
        tags: factorio-test-headless:latest

    - name: Build and run Docker tests
      run: |
        ls /opt/factorio/*
        ls /opt/factorio/bin
        docker run -it factorio-test-headless run-factorio-test --factorio_executable /opt/factorio/bin/factorio
        echo "done?"
    # - name: Set up environment
    #   run: |
    #     sudo apt-get update
    #     sudo apt-get install -y lua5.3

    # - name: Run local tests
    #   run: |
    #     cd tests/factorio-check
    #     lua main.lua

